# CGET 200
GET http://127.0.0.1:80/api/v1/notificaciones
Accept: application/json

# OPTIONS 422 (Mal ID)
OPTIONS http://127.0.0.1:80/api/v1/notificaciones/1

# OPTIONS 204
OPTIONS http://127.0.0.1:80/api/v1/notificaciones/1234-1234-12

