# CGET 200
GET http://127.0.0.1:80/api/v1/notificaciones
Accept: application/json

###
# OPTIONS 204
OPTIONS http://127.0.0.1:80/api/v1/notificaciones

###
# POST 201
POST http://127.0.0.1:80/api/v1/notificaciones
Content-Type: application/json

{
    "id" : "1234-1234-12",
    "id_trabajo" : "1234-1234",
    "estado" : "Creado"
}

# Operaciones por id de notificacion

###
# GET 200
GET http://127.0.0.1:80/api/v1/notificaciones/1234-1234-12
Accept: application/json

###
# GET 422 (Mal ID)
GET http://127.0.0.1:80/api/v1/notificaciones/1
Accept: application/json

###
# OPTIONS 422 (Mal ID)
OPTIONS http://127.0.0.1:80/api/v1/notificaciones/1

###
# OPTIONS 204
OPTIONS http://127.0.0.1:80/api/v1/notificaciones/1234-1234-12

# Operaciones por id de trabajo

###
# GET 200
GET http://127.0.0.1:80/api/v1/notificaciones/trabajo/1234-1234
Accept: application/json

###
# GET 422 (Mal ID)
GET http://127.0.0.1:80/api/v1/notificaciones/trabajo/1
Accept: application/json

###
# OPTIONS 422 (Mal ID)
OPTIONS http://127.0.0.1:80/api/v1/notificaciones/trabajo/1

###
# OPTIONS 204
OPTIONS http://127.0.0.1:80/api/v1/notificaciones/trabajo/1234-1234


