# curl -I -X "GET" "http://127.0.0.1:8000/notificaciones"  -H "accept: application/json"
GET http://127.0.0.1:8000/notificaciones
accept: application/json

###

# curl -I -X "GET" "http://127.0.0.1:8000/notificaciones?page=1&order=id&ordering=ASC"  -H "accept: application/json"
GET http://127.0.0.1:8000/notificaciones?page=1&order=id&ordering=ASC
accept: application/json

###

# curl -I -X "GET" "http://127.0.0.1:8000/notificaciones?page=1&order=id&ordering=ASC"  -H "accept: application/json"
GET http://127.0.0.1:8000/notificaciones?page=1&order=id&ordering=ASC
accept: application/json

###

# curl -I -X "GET" "http://127.0.0.1:8000/notificaciones?page=1&order=id_trabajo&ordering=ASC"  -H "accept: application/json"
GET http://127.0.0.1:8000/notificaciones?page=1&order=id_trabajo&ordering=ASC
accept: application/json

###

# curl -I -X "GET" "http://127.0.0.1:8000/notificaciones?page=1&order=id_trabajo&ordering=DESC"  -H "accept: application/json"
GET http://127.0.0.1:8000/notificaciones?page=1&order=id_trabajo&ordering=DESC
accept: application/json

###

# curl -I -X "GET" "http://127.0.0.1:8000/notificaciones"  -H "accept: application/json" -H "authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJBT1MgMjAyMyAtIEFQSSBOb3RpZmljYWNpb25lcyIsImF1ZCI6IkFPUyBVUE0iLCJzdWIiOiJhbGVqYW5kcm8uY2FycmFzY28uYXJhZ29uQGFsdW1ub3MudXBtLmVzIiwiZXhwIjoxNjkwMTMyMjc3LjI0NTQwNjIsImlhdCI6MTY4NDk0ODI3Ny4yNDU0MDYyfQ.AxIHGOn0RuSpJz5ALxJF3TxhfwNt8A30_jrFblRxZH8
GET http://127.0.0.1:8000/notificaciones
accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJBT1MgMjAyMyAtIEFQSSBOb3RpZmljYWNpb25lcyIsImF1ZCI6IkFPUyBVUE0iLCJzdWIiOiJhbGVqYW5kcm8uY2FycmFzY28uYXJhZ29uQGFsdW1ub3MudXBtLmVzIiwiZXhwIjoxNjkwMTMyMjc3LjI0NTQwNjIsImlhdCI6MTY4NDk0ODI3Ny4yNDU0MDYyfQ.AxIHGOn0RuSpJz5ALxJF3TxhfwNt8A30_jrFblRxZH8

###

# curl -I -X "GET" "http://127.0.0.1:8000/notificaciones"  -H "accept: application/json" -H "authorization: Bearer 1"
GET http://127.0.0.1:8000/notificaciones
accept: application/json
Authorization: Bearer 1

###
# curl -X "POST"   "http://127.0.0.1:8000/notificaciones"   -H "accept: application/json"   -H "Content-Type: application/json"   -d "{  \"id_trabajo\": \"1\",  \"estado\": \"Creado\",  \"detalle\": \"Detalles\"}"
POST http://127.0.0.1:8000/notificaciones
accept: application/json
Content-Type: application/json

{
  "id_trabajo": "1",
  "estado": "Creado",
  "detalle": "Detalles",
  "fecha_emision": "2023-04-05 12:00:58"
}

###

# curl -I -X "POST"   "http://127.0.0.1:8000/notificaciones"   -H "accept: application/json"   -H "Content-Type: application/json"   -d "{  \"estado\": \"Creado\",  \"detalle\": \"Detalles\"}"
POST http://127.0.0.1:8000/notificaciones
accept: application/json
Content-Type: application/json

{
  "estado": "Creado",
  "detalle": "Detalles",
  "fecha_emision": "2023-04-05 12:00:58"
}

###
# curl -I -X "POST"   "http://127.0.0.1:8000/notificaciones"   -H "accept: application/json"   -H "Content-Type: application/json"   -d "{  \"id_trabajo\": \"1\", \"estado\": \"Planificado\",  \"detalle\": \"Detalles\"}"
POST http://127.0.0.1:8000/notificaciones
accept: application/json
Content-Type: application/json

{
  "id_trabajo": "1",
  "estado": "Planificado",
  "detalle": "Detalles",
  "fecha_emision": "2023-04-05 12:00:58"
}

###

# curl -I -X "POST"   "http://127.0.0.1:8000/notificaciones"   -H "accept: application/json"   -H "Content-Type: application/json"   -d "{  \"id_trabajo\": \"1234-1235\",  \"estado\": \"Iniciado\",  \"detalle\": \"Detalles\"}"
POST http://127.0.0.1:8000/notificaciones
accept: application/json
Content-Type: application/json

{
  "id_trabajo": "1234-1236",
  "estado": "Iniciado",
  "detalle": "Detalles",
  "fecha_emision": "2023-04-05 12:00:58"
}

###
# curl -I -X "OPTIONS" "http://127.0.0.1:8000/notificaciones" -H "accept: */*"
OPTIONS http://127.0.0.1:8000/notificaciones
accept: */*

###
# curl -I -X "GET" "http://127.0.0.1:8000/notificaciones/1234-1234"  -H "accept: application/json"
GET http://127.0.0.1:8000/notificaciones/1234-1234
accept: application/json

###
# curl -I -X "GET" "http://127.0.0.1:8000/notificaciones/1234-1234"  -H "accept: application/json" -H "authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJBT1MgMjAyMyAtIEFQSSBOb3RpZmljYWNpb25lcyIsImF1ZCI6IkFPUyBVUE0iLCJzdWIiOiJhbGVqYW5kcm8uY2FycmFzY28uYXJhZ29uQGFsdW1ub3MudXBtLmVzIiwiZXhwIjoxNjkwMTMyMjc3LjI0NTQwNjIsImlhdCI6MTY4NDk0ODI3Ny4yNDU0MDYyfQ.AxIHGOn0RuSpJz5ALxJF3TxhfwNt8A30_jrFblRxZH8
GET http://127.0.0.1:8000/notificaciones/1234-1234
accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJBT1MgMjAyMyAtIEFQSSBOb3RpZmljYWNpb25lcyIsImF1ZCI6IkFPUyBVUE0iLCJzdWIiOiJhbGVqYW5kcm8uY2FycmFzY28uYXJhZ29uQGFsdW1ub3MudXBtLmVzIiwiZXhwIjoxNjkwMTMyMjc3LjI0NTQwNjIsImlhdCI6MTY4NDk0ODI3Ny4yNDU0MDYyfQ.AxIHGOn0RuSpJz5ALxJF3TxhfwNt8A30_jrFblRxZH8

###
# curl -I -X "OPTIONS" "http://127.0.0.1:8000/notificaciones/1234-1234" -H "accept: */*"
OPTIONS http://127.0.0.1:8000/notificaciones/1234-1234
accept: */*

###
# curl -I -X "DELETE" "http://127.0.0.1:8000/notificaciones/0000-0001" -H "accept: */*"
DELETE http://127.0.0.1:8000/notificaciones/0000-0001
accept: */*

###
# curl -I -X "DELETE" "http://127.0.0.1:8000/notificaciones/1234-1234-1" -H "accept: */*"
DELETE http://127.0.0.1:8000/notificaciones/0000-0002
accept: */*
