apiVersion: v1
kind: Pod
metadata:
  name: aos-entrega
spec:
  containers:
  - name: aos-entrega
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    volumeMounts:
      - mountPath: /aos
        name: volume
  volumes:
    - name: volume
      hostPath:
        path: /home/azureuser/AOS/Entrega
