apiVersion: v1
kind: Pod
metadata:
  name: aos-entrega
spec:
  containers:
  - name: aos-entrega
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    volumeMounts:
      - mountPath: /aos
        name: volume
  volumes:
    - name: volume
      hostPath:
<<<<<<< HEAD
        path: /home/azureuser/AOS/Entrega
=======
        path: /home/azureuser/AOS/Entrega   

>>>>>>> ff364f2a3fe91d2a5604ce2c25609d082fc4238c
