apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    volumeMounts:
      - mountPath: /aos
        name: volume
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: disco-notificaciones    

