apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: azure-managed-disk
spec:
  accessModes:
  - ReadWriteOnce
#  storageClassName: standard
  storageClassName: managed-csi
  resources:
    requests:
      storage: 5Gi
  dataSource:
    name: aos-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io