apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\temp\git\AOS_2023_Practica_1\kompose-windows-amd64.exe convert -f ../practica_2/docker-compose.yml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: clientes-mock-backend
  name: clientes_mock_backend
spec:
  ports:
    - name: "4010"
      port: 4010
      targetPort: 4010
  selector:
    io.kompose.service: clientes-mock-backend
status:
  loadBalancer: {}
