apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: disco-notificaciones
spec:
  storageClassName: azurefile-csi
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 5Gi
