apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\tmp\git\AOS_2023_Practica_1\kompose-windows-amd64.exe convert -f ../practica_2/docker-compose.yml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: facturas-mock-backend
  name: facturas-mock-backend
spec:
  type: ClusterIP
  ports:
    - name: "4012"
      port: 4012
      targetPort: 4010
  selector:
    io.kompose.service: facturas-mock-backend
