apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\tmp\git\AOS_2023_Practica_1\kompose-windows-amd64.exe convert -f ../practica_2/docker-compose.yml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: notificaciones-backend
  name: notificaciones-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: notificaciones-backend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\tmp\git\AOS_2023_Practica_1\kompose-windows-amd64.exe convert -f ../practica_2/docker-compose.yml
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/practica-2-default: "true"
        io.kompose.service: notificaciones-backend
    spec:
      containers:
        - args:
            - uvicorn
            - main:app
            - --host
            - 0.0.0.0
            - --port
            - "4013"
          env:
            - name: URL_TRABAJOS
              value: http://trabajos-mock-backend:4015
            - name: SQLALCHEMY_DATABASE_URI
              value: sqlite:////app/server/notificaciones.db
          image: acarrasco2000/aos2023-notificaciones:v1
          name: aos2023-notificaciones
          ports:
            - containerPort: 4013
          resources: {}
          volumeMounts:
            - mountPath: /aos
              name: volume
      restartPolicy: Always
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: disco-notificaciones    
status: {}
