apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\tmp\git\AOS_2023_Practica_1\kompose-windows-amd64.exe convert -f ../practica_2/docker-compose.yml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: recambios-frontend
  name: recambios-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: recambios-frontend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\tmp\git\AOS_2023_Practica_1\kompose-windows-amd64.exe convert -f ../practica_2/docker-compose.yml
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/practica-2-default: "true"
        io.kompose.service: recambios-frontend
    spec:
      containers:
        - env:
            - name: SWAGGER_JSON
              value: /aos/practica_2/especificaciones/Recambios/openapi.yaml
          image: swaggerapi/swagger-ui:latest
          name: aos2023-recambios-ui
          ports:
            - containerPort: 8080
          resources: {}

          volumeMounts:
            - mountPath: /aos
              name: recambios-frontend-hostpath0
              readOnly: true
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /home/azureuser/AOS/Entrega
          name: recambios-frontend-hostpath0

status: {}
