apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\temp\git\AOS_2023_Practica_1\kompose-windows-amd64.exe convert -f ../practica_2/docker-compose.yml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: trabajos-mock-backend
  name: trabajos_mock_backend
spec:
  ports:
    - name: "4015"
      port: 4015
      targetPort: 4015
  selector:
    io.kompose.service: trabajos-mock-backend
status:
  loadBalancer: {}
