apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\tmp\git\AOS_2023_Practica_1\kompose-windows-amd64.exe convert -f ../practica_2/docker-compose.yml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: vehiculos-mock-backend
  name: vehiculos-mock-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vehiculos-mock-backend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\tmp\git\AOS_2023_Practica_1\kompose-windows-amd64.exe convert -f ../practica_2/docker-compose.yml
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/practica-2-default: "true"
        io.kompose.service: vehiculos-mock-backend
    spec:
      containers:
        - args:
            - mock
            - --cors
            - -h
            - 0.0.0.0
            - /aos/especificaciones/Vehiculos/openapi.yaml
          image: stoplight/prism:4
          name: aos2023-vehiculos-mock
          ports:
            - containerPort: 4010
          resources: {}

          volumeMounts:
            - mountPath: /aos
              name: vehiculos-mock-backend-hostpath0
              readOnly: true
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /home/azureuser/AOS/Entrega/especificaciones
          name: vehiculos-mock-backend-hostpath0

status: {}
