apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\temp\git\AOS_2023_Practica_1\kompose-windows-amd64.exe convert -f ../practica_2/docker-compose.yml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: vehiculos-frontend
  name: vehiculos_frontend
spec:
  ports:
    - name: "8006"
      port: 8006
      targetPort: 8086
  selector:
    io.kompose.service: vehiculos-frontend
status:
  loadBalancer: {}
