version: "3.9"

services:

    # En los comandos de prism mock se puede indicar el puerto con la opción "-p". Por defecto es 4010.
    # ports: define el mapeo de puerto externo a interno. Para swagger-ui el puerto interno es el 8080.

    clientes-mock-backend:
      image: stoplight/prism:4
      container_name: aos2023-clientes-mock
      command: mock --cors -h 0.0.0.0 "/aos/openapi.yml"
      ports:
        - "4010:4010"
      volumes:
        - ./especificaciones/Clientes:/aos:ro

    clientes-frontend:
      image: swaggerapi/swagger-ui:latest
      container_name: aos2023-clientes-ui
      ports:
        - "8000:8080"
      environment:
        SWAGGER_JSON: /aos/openapi.yml
      volumes:
        - ./especificaciones/Clientes:/aos:ro

    logs-mock-backend:
      image: stoplight/prism:4
      container_name: aos2023-logs-mock
      command: mock --cors -h 0.0.0.0 "/aos/openapi.yml"
      ports:
        - "4011:4010"
      volumes:
        - ./especificaciones/Logs:/aos:ro

    logs-frontend:
      image: swaggerapi/swagger-ui:latest
      container_name: aos2023-logs-ui
      ports:
        - "8001:8080"
      environment:
        SWAGGER_JSON: /aos/openapi.yml
      volumes:
        - ./especificaciones/Logs:/aos:ro

    facturas-mock-backend:
      image: stoplight/prism:4
      container_name: aos2023-facturas-mock
      command: mock --cors -h 0.0.0.0 "/aos/openapi.yaml"
      ports:
        - "4012:4010"
      volumes:
        - ./especificaciones/Facturas:/aos:ro

    facturas-frontend:
      image: swaggerapi/swagger-ui:latest
      container_name: aos2023-facturas-ui
      ports:
        - "8002:8080"
      environment:
        SWAGGER_JSON: /aos/openapi.yaml
      volumes:
        - ./especificaciones/Facturas:/aos:ro

    notificaciones-backend:
      image: acarrasco2000/aos2023-notificaciones:v1
      container_name: aos2023-notificaciones
      command: uvicorn main:app --host 0.0.0.0 --port 4013
      ports:
        - "4013:4013"
      environment:
        URL_TRABAJOS: http://localhost:4015
      volumes:
        - ./especificaciones/Notificaciones:/aos:ro

    recambios-mock-backend:
      image: stoplight/prism:4
      container_name: aos2023-recambios-mock
      command: mock --cors -h 0.0.0.0 "/aos/openapi.yaml"
      ports:
        - "4014:4010"
      volumes:
        - ./especificaciones/Recambios:/aos:ro

    recambios-frontend:
      image: swaggerapi/swagger-ui:latest
      container_name: aos2023-recambios-ui
      ports:
        - "8004:8080"
      environment:
        SWAGGER_JSON: /aos/openapi.yaml
      volumes:
        - ./especificaciones/Recambios:/aos:ro

    trabajos-mock-backend:
      image: stoplight/prism:4
      container_name: aos2023-trabajos-mock
      command: mock --cors -h 0.0.0.0 "/aos/openapi.yaml"
      ports:
        - "4015:4010"
      volumes:
        - ./especificaciones/Trabajos:/aos:ro

    trabajos-frontend:
      image: swaggerapi/swagger-ui:latest
      container_name: aos2023-trabajos-ui
      ports:
        - "8005:8080"
      environment:
        SWAGGER_JSON: /aos/openapi.yaml
      volumes:
        - ./especificaciones/Trabajos:/aos:ro

    vehiculos-mock-backend:
      image: stoplight/prism:4
      container_name: aos2023-vehiculos-mock
      command: mock --cors -h 0.0.0.0 "/aos/openapi.yaml"
      ports:
        - "4016:4010"
      volumes:
        - ./especificaciones/Vehiculos:/aos:ro

    vehiculos-frontend:
      image: swaggerapi/swagger-ui:latest
      container_name: aos2023-vehiculos-ui
      ports:
        - "8006:8080"
      environment:
        SWAGGER_JSON: /aos/openapi.yaml
      volumes:
        - ./especificaciones/Vehiculos:/aos:ro
