version: "3.9"

services:
    # Mock-ups para los servicios: Clientes, Facturas, Notificaciones, Recambios, Trabajos y Vehiculos

    clientes_mock_backend:
      image: stoplight/prism:4
      container_name: aos2023_clientes_mock
      command: mock --cors -h 0.0.0.0 -p 4010 "/aos/clientes/openapi.yml"
      ports:
        - "4010:4010"
      volumes:
        - ./especificaciones:/aos:ro

    facturas_mock_backend:
      image: stoplight/prism:4
      container_name: aos2023_facturas_mock
      command: mock --cors -h 0.0.0.0 -p 4011 "/aos/facturas/openapi.yaml"
      ports:
        - "4011:4011"
      volumes:
        - ./especificaciones:/aos:ro

    notificaciones_mock_backend:
      image: stoplight/prism:4
      container_name: aos2023_notificaciones_mock
      command: mock --cors -h 0.0.0.0 -p 4012 "/aos/notificaciones/openapi.yaml"
      ports:
        - "4012:4012"
      volumes:
        - ./especificaciones:/aos:ro

    recambios_mock_backend:
      image: stoplight/prism:4
      container_name: aos2023_recambios_mock
      command: mock --cors -h 0.0.0.0 -p 4013 "/aos/recambios/openapi.yaml"
      ports:
        - "4013:4013"
      volumes:
        - ./especificaciones:/aos:ro

    trabajos_mock_backend:
      image: stoplight/prism:4
      container_name: aos2023_trabajos_mock
      command: mock --cors -h 0.0.0.0 -p 4014 "/aos/trabajos/openapi.yaml"
      ports:
        - "4014:4014"
      volumes:
        - ./especificaciones:/aos:ro

    vehiculos_mock_backend:
      image: stoplight/prism:4
      container_name: aos2023_vehiculos_mock
      command: mock --cors -h 0.0.0.0 -p 4015 "/aos/vehiculos/openapi.yaml"
      ports:
        - "4015:4015"
      volumes:
        - ./especificaciones:/aos:ro
